Add another orphan instance for Compose
obsidiansystems/vessel pull request #14
Opened 2021-10-15 16:21 UTC by madeline-os

This instance is more in the same vein as the other Compose orphans in the same place, to make Vessels usable with obelisk/rhyolite.

I've also added a cabal.project file so that it's easier to work with Vessel as a dep inside of a larger project.

@Ericson2314 told me a bunch of stuff about how this is fucked up in base upstream. I have to go through his notes and  turn them into a plan that deals with this situation properly. :)

2021-10-15 16:43 UTC, Ericson2314 reviewed
~~This should go in `patch` not here, then it won't be an orphan~~ Oh I see it is with the others in that module, sorry.

2021-11-02 00:55 UTC, ali-abrar requested changes
Please update the changelog. If there's further work to be done (later, when base is updated, perhaps), maybe open an issue so we don't forget.

2021-11-02 01:18 UTC, Ericson2314 requested changes
We can put these in `patch` after since base-orphans has these after all https://hackage.haskell.org/package/base-orphans-0.8.6/docs/Data-Orphans.html#v:-36-fMonoidCompose

2021-11-12 15:17 UTC, merged

2021-11-12 15:30 UTC, Ericson2314 commented on ChangeLog.md
> +## 0.1.1.0
We typically have gone newest first, FYI.